//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tasks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public Nullable<int> HaircutId { get; set; }
        public string ClientName { get; set; }
        public string ClientPhone { get; set; }
        public System.DateTime AppointmentDate { get; set; }
        public System.TimeSpan StartTime { get; set; }
        public System.TimeSpan EndTime { get; set; }
    
        public virtual Haircuts Haircuts { get; set; }
        public virtual Masters Masters { get; set; }
    }
}
